# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fUie8uDZmjsDa9Wn2LnpSVcSLewE-t_L
"""

import pandas as pd
import os
import json
from rapidfuzz import process, fuzz

# CSV dosyasını oku
df = pd.read_csv("/content/datadux8.csv")

# Görsellerin ve teknik çizimlerin bulunduğu klasörler
image_folder = "/content/drive/My Drive/Askı Sapanları - Tüm ürünler"
technical_drawings_folder = "/content/drive/My Drive/Askı Sapanları - Tüm ürünler"

# Harfleri küçült ve boşlukları kaldır
df["resim_dosyasi_normalized"] = df["resim_dosyasi"].str.lower().str.replace(" ", "_")

# Eşleşme oranı belirleyerek aynı fotoğrafı paylaşan ürünleri gruplama
unique_products = {}
unmatched_products = []  # Eşleşmeyen ürünleri saklamak için liste

def find_best_match(product_name):
    if unique_products:
        result = process.extractOne(product_name, unique_products.keys(), scorer=fuzz.ratio)
        if result and result[1] > 60:  # Eşleşme oranı yeterince yüksekse
            return result[0], result[1]
    return None, None

for urun in df["resim_dosyasi_normalized"].unique():
    match, score = find_best_match(urun)
    if match:
        unique_products[match].append(urun)
    else:
        unique_products[urun] = [urun]
        unmatched_products.append(urun)  # Eşleşmeyen ürünü kaydet

# Ürünleri güncellenmiş isimlerle eşleştir
mapping = {urun: match for match, urunler in unique_products.items() for urun in urunler}
df["urun_ismi_matched"] = df["resim_dosyasi_normalized"].map(mapping)

# Görselleri ve teknik çizimleri dosya yollarına ekle (".jpg" uzantısını yok sayarak)
df["resim_dosyasi_normalized"] = df["urun_ismi_matched"].apply(lambda x: os.path.join(image_folder, f"{x}.jpg"))
df["teknik_cizim"] = df["urun_ismi_matched"].apply(lambda x: os.path.join(technical_drawings_folder, f"{x}.png"))

# JSON formatına çevir
json_data = df.to_dict(orient="records")

# JSON dosyasına kaydet
with open("urunler1.json", "w", encoding="utf-8") as json_file:
    json.dump(json_data, json_file, ensure_ascii=False, indent=4)

# Eşleşmeyen ürünleri ayrı bir JSON dosyasına kaydet
with open("eslesmeyenler1.json", "w", encoding="utf-8") as json_file:
    json.dump(unmatched_products, json_file, ensure_ascii=False, indent=4)

print("JSON dosyası oluşturuldu!")
print(f"Eşleşmeyen {len(unmatched_products)} ürün tespit edildi. Detaylar 'eslesmeyenler.json' dosyasına kaydedildi.")

from datasets import load_dataset

dataset = load_dataset("json", data_files="/content/urunler1.json")
dataset = dataset["train"]  # Eğitim verisi olarak tanımla

import pandas as pd
import json
import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel, TrainingArguments, Trainer
from datasets import Dataset
import torch.nn.functional as F

# JSON dosyasını oku
with open("/content/urunler1.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

for item in data:
    for key, value in item.items():
        if isinstance(value, float):
            item[key] = str(value)

# Dataset oluştur
dataset = Dataset.from_list(data)

# Model ve işlemci yükleme
model_name = "openai/clip-vit-base-patch32"
model = CLIPModel.from_pretrained(model_name)
processor = CLIPProcessor.from_pretrained(model_name)

class CLIPDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, processor):
        self.dataset = dataset
        self.processor = processor

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        item = self.dataset[idx]

        # Görüntüyü yükle ve işle
        image = Image.open(item["image"]).convert("RGB")

        # Processor'ı uygula
        inputs = self.processor(
            text=[item["text"]],
            images=image,
            return_tensors="pt",
            padding='max_length',  # Maksimum uzunluğa kadar padding yap
            truncation=True,
            max_length=77,         # CLIP'in maksimum token uzunluğu
        )

        # Batch boyutunu kaldır
        for key in inputs.keys():
            inputs[key] = inputs[key].squeeze()

        return inputs

def collate_fn(batch):
    batch_size = len(batch)

    # Maksimum uzunluğu bul
    max_len = max(item['input_ids'].size(0) for item in batch)

    # Tensörleri hazırla
    input_ids = torch.zeros(batch_size, max_len, dtype=torch.long)
    attention_mask = torch.zeros(batch_size, max_len, dtype=torch.long)
    pixel_values = torch.stack([item['pixel_values'] for item in batch])

    # Her örneği pad'le
    for i, item in enumerate(batch):
        input_len = item['input_ids'].size(0)
        input_ids[i, :input_len] = item['input_ids']
        attention_mask[i, :input_len] = item['attention_mask']

    return {
        'input_ids': input_ids,
        'attention_mask': attention_mask,
        'pixel_values': pixel_values,
    }

# Dataset'i özel formata dönüştür
train_dataset = CLIPDataset(dataset, processor)

# Eğitim argümanları
training_args = TrainingArguments(
    output_dir="./clip_model",
    per_device_train_batch_size=4,
    num_train_epochs=10,
    learning_rate=5e-6,
    save_steps=500,
    logging_dir="./logs",
    logging_steps=100,
    dataloader_drop_last=True,
    remove_unused_columns=False
)

# Özel loss hesaplama fonksiyonu
class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, num_items_in_batch=None, return_outputs=False):
        outputs = model(**inputs)

        # Görüntü ve metin embedding'leri
        image_embeds = outputs.image_embeds
        text_embeds = outputs.text_embeds

        # Benzerlik skoru hesaplama
        logits_per_image = image_embeds @ text_embeds.T
        logits_per_text = text_embeds @ image_embeds.T

        # Hedefler oluştur
        labels = torch.arange(logits_per_image.size(0), device=logits_per_image.device)

        # Cross-Entropy Loss hesapla
        loss_img = F.cross_entropy(logits_per_image, labels)
        loss_txt = F.cross_entropy(logits_per_text, labels)
        loss = (loss_img + loss_txt) / 2

        return (loss, outputs) if return_outputs else loss

# Trainer nesnesi oluştur
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    data_collator=collate_fn

)

# Eğitimi başlat
print("Eğitim başlıyor...")
try:
    trainer.train()
    print("Eğitim başarıyla tamamlandı!")

    # Modeli kaydet
    model.save_pretrained("./clip_model_final")
    processor.save_pretrained("./clip_model_final")
    print("Model kaydedildi!")

except Exception as e:
    print(f"Eğitim sırasında hata oluştu: {str(e)}")
    import traceback
    traceback.print_exc()

import pandas as pd
import json
import torch
from PIL import Image
from transformers import CLIPProcessor, CLIPModel, TrainingArguments, Trainer
from datasets import Dataset
import torch.nn.functional as F
import os
from tqdm import tqdm

def prepare_data(data):
    """Veriyi CLIP eğitimi için hazırla"""
    prepared_data = []
    for item in data:
        prepared_item = {
            "image": item["resim_dosyasi"],  # resim_dosyasi'nı image olarak kullan
            "text": item['urun_ismi']  # Sadece ürün ismini kullan
        }
        prepared_data.append(prepared_item)
    return prepared_data

def validate_data(data):
    """Veri setini doğrula ve eksik/hatalı öğeleri raporla"""
    valid_data = []
    for idx, item in enumerate(data):
        is_valid = True
        if "resim_dosyasi" not in item:
            print(f"Hata: {idx}. öğede 'resim_dosyasi' anahtarı eksik")
            is_valid = False
        if "urun_ismi" not in item or "aciklama" not in item:
            print(f"Hata: {idx}. öğede 'urun_ismi' veya 'aciklama' anahtarı eksik")
            is_valid = False
        if is_valid:
            if not os.path.exists(item["resim_dosyasi"]):
                print(f"Uyarı: {item['resim_dosyasi']} dosyası bulunamadı")
                is_valid = False
        if is_valid:
            valid_data.append(item)
    return valid_data

# JSON dosyasını oku ve doğrula
print("Veri yükleniyor...")
with open("/content/urunler1.json", 'r', encoding='utf-8') as f:
    data = json.load(f)

# Veriyi doğrula
print("Veri doğrulanıyor...")
valid_data = validate_data(data)
if not valid_data:
    raise ValueError("Geçerli veri bulunamadı!")

# Veriyi hazırla
prepared_data = prepare_data(valid_data)
print(f"Toplam {len(prepared_data)} geçerli örnek hazırlandı.")

# Dataset oluştur
dataset = Dataset.from_list(prepared_data)

# Model ve işlemci yükleme
print("Model yükleniyor...")
model_name = "openai/clip-vit-base-patch32"
try:
    model = CLIPModel.from_pretrained(model_name)
    processor = CLIPProcessor.from_pretrained(model_name)
except Exception as e:
    raise Exception(f"Model yüklenirken hata oluştu: {str(e)}")

class CLIPDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, processor):
        self.dataset = dataset
        self.processor = processor

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        try:
            item = self.dataset[idx]
            image = Image.open(item["image"]).convert("RGB")

            inputs = self.processor(
                text=[item["text"]],
                images=image,
                return_tensors="pt",
                padding='max_length',
                truncation=True,
                max_length=77,
            )

            # Batch boyutunu kaldır
            for key in inputs.keys():
                inputs[key] = inputs[key].squeeze()

            return inputs
        except Exception as e:
            print(f"Örnek {idx} işlenirken hata oluştu: {str(e)}")
            raise

def collate_fn(batch):
    try:
        batch_size = len(batch)
        max_len = max(item['input_ids'].size(0) for item in batch)

        input_ids = torch.zeros(batch_size, max_len, dtype=torch.long)
        attention_mask = torch.zeros(batch_size, max_len, dtype=torch.long)
        pixel_values = torch.stack([item['pixel_values'] for item in batch])

        for i, item in enumerate(batch):
            input_len = item['input_ids'].size(0)
            input_ids[i, :input_len] = item['input_ids']
            attention_mask[i, :input_len] = item['attention_mask']

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'pixel_values': pixel_values,
        }
    except Exception as e:
        print(f"Batch işlenirken hata oluştu: {str(e)}")
        raise

# Dataset'i özel formata dönüştür
print("Dataset hazırlanıyor...")
train_dataset = CLIPDataset(dataset, processor)

# Eğitim argümanları
training_args = TrainingArguments(
    output_dir="./clip_model",
    per_device_train_batch_size=4,
    num_train_epochs=10,
    learning_rate=5e-6,
    save_steps=500,
    logging_dir="./logs",
    logging_steps=100,
    dataloader_drop_last=True,
    remove_unused_columns=False
)

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, num_items_in_batch=None, return_outputs=False):
        try:
            outputs = model(**inputs)

            image_embeds = outputs.image_embeds
            text_embeds = outputs.text_embeds

            logits_per_image = image_embeds @ text_embeds.T
            logits_per_text = text_embeds @ image_embeds.T

            labels = torch.arange(logits_per_image.size(0), device=logits_per_image.device)

            loss_img = F.cross_entropy(logits_per_image, labels)
            loss_txt = F.cross_entropy(logits_per_text, labels)
            loss = (loss_img + loss_txt) / 2

            return (loss, outputs) if return_outputs else loss
        except Exception as e:
            print(f"Loss hesaplanırken hata oluştu: {str(e)}")
            raise

# Trainer nesnesi oluştur
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    data_collator=collate_fn
)

# Eğitimi başlat
print("Eğitim başlıyor...")
try:
    trainer.train()
    print("Eğitim başarıyla tamamlandı!")

    # Modeli kaydet
    print("Model kaydediliyor...")
    model.save_pretrained("./clip_model_final")
    processor.save_pretrained("./clip_model_final")
    print("Model başarıyla kaydedildi!")

except Exception as e:
    print(f"Eğitim sırasında hata oluştu: {str(e)}")
    import traceback
    traceback.print_exc()